# Generated by Django 4.0.1 on 2022-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Completed', 'In Completed')], max_length=200, null=True),
        ),
    ]
