# Generated by Django 4.0.1 on 2022-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Complete', 'In Complete')], max_length=200, null=True),
        ),
    ]
