# Generated by Django 4.0.1 on 2022-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
